import "../pages.css";

function Blog() {

  return (
    <div className="page">
      <div className="wrapper">
        <h1>Blog</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vestibulum sapien non felis accumsan, quis interdum ipsum imperdiet. Nunc eget porta magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam eu auctor dui, in tincidunt metus. Integer faucibus ultrices ultricies. Mauris sed justo risus. Mauris fringilla velit in vulputate sollicitudin. Etiam vitae placerat metus. Donec scelerisque justo eget sollicitudin lobortis. Mauris interdum odio vel lectus lobortis commodo. Praesent commodo arcu at tellus tempor, placerat elementum quam dignissim. Phasellus eget urna erat. Integer orci ex, vehicula nec faucibus et, gravida id purus. Integer porttitor lacus ac enim rhoncus, ut cursus leo rhoncus. Maecenas euismod risus nec justo faucibus tincidunt.</p>
        <p>Ut faucibus est at lacinia volutpat. Mauris vel felis ac dolor lobortis scelerisque at elementum lectus. Sed imperdiet augue id lorem lobortis vehicula id ac arcu. Phasellus lacinia turpis ut libero semper, vitae dapibus lectus bibendum. Nullam pretium cursus mauris, ac sodales est. Integer ut elit in felis pulvinar volutpat vitae in leo. Duis non risus sollicitudin, tempor magna sed, rhoncus elit. Praesent elementum ipsum eget fringilla posuere. Vivamus ac enim quis ante commodo semper id ut neque. Phasellus aliquet hendrerit erat, in auctor enim vulputate a. Nullam congue pharetra suscipit. Nunc condimentum id elit nec efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
        <p>Proin sed nisl justo. In at nisi dapibus, fringilla sem ac, facilisis orci. Morbi molestie interdum erat, et maximus diam lobortis vel. Donec sodales urna a feugiat gravida. Donec pretium lobortis justo, a bibendum orci. Aenean vel eros nisl. Integer sit amet feugiat sem. Fusce id tempor magna. Integer aliquet mauris neque, id sollicitudin orci tincidunt a. Phasellus aliquam sit amet odio nec feugiat. Curabitur turpis erat, lacinia ac ipsum sit amet, porta blandit velit. Phasellus at elit quis quam gravida rutrum. Aenean malesuada massa sed magna gravida accumsan. Vivamus quis tellus non elit suscipit porttitor. Cras nec fermentum nisi.</p>
        <p>Etiam ut lectus ac lectus laoreet porttitor in at diam. Donec enim ex, malesuada sed risus vel, sollicitudin suscipit enim. Morbi bibendum viverra enim, at malesuada lacus elementum at. Etiam pretium sem magna, vitae maximus erat finibus id. Fusce tincidunt urna sit amet diam egestas tristique. In mattis faucibus lacus quis fermentum. Donec luctus lacus felis, quis iaculis neque lacinia at. Nullam elementum hendrerit elit, in fermentum nisl porttitor at. Integer rutrum tempus nibh nec tempor. Sed felis leo, euismod eu egestas eu, facilisis eget mauris. Nunc id ipsum odio. Vestibulum ut orci sit amet dui placerat pellentesque non semper ex. Fusce ultricies erat id posuere tristique. Praesent in felis sed nunc semper maximus non auctor mauris.</p>
        <p>Aliquam erat volutpat. Vivamus vel nulla quis libero viverra blandit sed eget ligula. Vivamus malesuada congue justo a sagittis. Curabitur rutrum neque vitae odio posuere congue. Morbi blandit felis et nisi finibus varius. Aliquam efficitur hendrerit nulla in tristique. Nulla ullamcorper auctor ante, id tincidunt ipsum mollis in. Quisque at laoreet sapien. Sed fermentum ipsum lectus, id laoreet lacus elementum vel. Nulla id tellus eget metus sodales congue. Sed viverra at leo dapibus convallis. Suspendisse luctus quis velit in elementum. Suspendisse libero velit, viverra quis laoreet molestie, mattis nec sapien. Aenean ante dolor, aliquam a eros et, porttitor rhoncus nibh. Nam non metus nunc. Sed varius posuere odio, id congue nibh imperdiet et.</p>
      </div>
    </div>
  );

}

export default Blog;