import "../pages.css";

function Episodes() {

  return (
    <div className="page">
      <div className="wrapper">
        <h1>Episodes</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur libero eget elit lobortis accumsan. Curabitur eget lorem libero. Proin rhoncus faucibus risus, quis semper orci suscipit non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque id justo aliquet, facilisis orci in, facilisis augue. Vivamus mollis consectetur nunc, sit amet gravida ligula volutpat id. Cras ac interdum augue. Mauris vel magna quis mi hendrerit tincidunt. Morbi euismod, ligula ac imperdiet ultricies, risus purus placerat lectus, at commodo tellus mauris eu leo. Maecenas pharetra erat mi, vitae faucibus turpis tristique in. Integer ut dolor at elit maximus molestie. Ut sed diam nec velit imperdiet tincidunt. Maecenas iaculis auctor semper. Quisque id hendrerit quam.</p>
        <p>Nullam sit amet efficitur tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque viverra neque sed pellentesque laoreet. Nulla sodales fermentum mi, sit amet pulvinar lacus viverra eget. Integer quis turpis eget lacus faucibus tempus. Etiam sed libero velit. Nunc in congue eros. Morbi in tempus lacus. Nam tempus, enim sit amet bibendum tempor, eros purus lobortis quam, sed ornare massa justo eget leo. Aenean lectus lorem, semper vitae mollis nec, pulvinar vitae augue. Nam ultricies erat libero, vel consectetur ligula elementum molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
        <p>Suspendisse vitae consequat magna, vel viverra arcu. Praesent hendrerit magna eros, nec finibus tortor aliquet in. Duis lacinia malesuada convallis. Phasellus pretium dictum arcu, in faucibus velit sodales nec. Morbi sit amet justo mi. Praesent dui nunc, finibus et nibh eget, pulvinar interdum nisi. Phasellus porta elit vel justo commodo aliquet. In iaculis sed orci vel vulputate. Mauris augue purus, cursus eget interdum auctor, tempor eget tortor. Vivamus ut erat consectetur, finibus erat vel, placerat magna. Vestibulum luctus scelerisque odio eget porttitor. Quisque commodo vestibulum nulla, at vestibulum nunc varius non. Mauris commodo sodales tempor. Sed posuere ultrices cursus. Donec at ex ac lacus viverra varius eget et nisl.</p>
        <p>Morbi aliquet, nunc quis tristique aliquam, diam libero dignissim mi, eget tempus tortor nulla vel erat. Integer nulla elit, porta at euismod quis, efficitur aliquet purus. In at justo ultrices, mattis massa ac, volutpat nibh. Fusce non massa ullamcorper felis tristique blandit quis sit amet nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin luctus, nulla et viverra egestas, magna purus fringilla ligula, ac mattis mi nulla in nisl. Etiam elementum est sit amet lorem varius, in egestas lacus ullamcorper. Pellentesque diam elit, aliquet vel hendrerit sit amet, aliquet et nunc. Donec imperdiet erat arcu, ac dignissim tortor feugiat et. Proin tincidunt lorem quis enim consequat, vitae consectetur nunc commodo. Donec odio tortor, tempor at mauris nec, faucibus porttitor nisl. Phasellus ut porttitor ipsum, non tempor augue.</p>
        <p>Nulla viverra aliquam mauris, ut sodales nisl accumsan vitae. Morbi vel nisl at libero tempor varius. Ut nisl tellus, porta et finibus et, dignissim vel lorem. Vestibulum tempus massa velit, ac euismod nisl porta nec. Nullam facilisis orci mauris, vitae blandit ipsum ultrices quis. Suspendisse potenti. Curabitur pellentesque imperdiet tellus, eu cursus elit porttitor et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus posuere placerat orci sed finibus. Ut sodales augue quis eros pretium egestas. Praesent dapibus, eros id iaculis mollis, elit justo rutrum ipsum, eget varius enim urna at odio. Suspendisse venenatis molestie arcu. Quisque consequat lectus ac mi malesuada, id blandit sapien sodales. Etiam ac sem ac metus interdum ultrices id eget turpis.</p>
      </div>
    </div>
  );

}

export default Episodes;