import "../pages.css";
import WikiOverview from "./wiki-page.js";
import WikiPage from "./wiki-page.js";

function WikiHome() {

  return (
    <div className="page">
      <div className="wrapper">
        <WikiOverview />
        <h1>Test Wiki</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Proin libero nunc consequat interdum varius sit amet mattis vulputate. Cras sed felis eget velit aliquet sagittis id consectetur purus. Neque convallis a cras semper auctor neque vitae tempus. Massa ultricies mi quis hendrerit. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. In eu mi bibendum neque egestas congue quisque. Tincidunt dui ut ornare lectus sit amet est placerat in. Elit at imperdiet dui accumsan sit amet nulla facilisi. Donec adipiscing tristique risus nec feugiat in fermentum posuere urna. Nunc mattis enim ut tellus elementum sagittis vitae. Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. Natoque penatibus et magnis dis parturient montes nascetur. Eget mi proin sed libero enim sed faucibus turpis. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Vehicula ipsum a arcu cursus vitae. Consectetur adipiscing elit pellentesque habitant morbi tristique.</p>
        <p>Dui sapien eget mi proin. Auctor urna nunc id cursus metus aliquam eleifend mi. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Morbi tristique senectus et netus et malesuada fames ac turpis. Iaculis urna id volutpat lacus laoreet non curabitur. Facilisis magna etiam tempor orci eu. Tortor pretium viverra suspendisse potenti nullam ac tortor. Feugiat vivamus at augue eget arcu. At augue eget arcu dictum varius duis at. Ultrices vitae auctor eu augue ut lectus. Mauris a diam maecenas sed. Euismod in pellentesque massa placerat duis. Sit amet justo donec enim diam vulputate ut pharetra. Sem nulla pharetra diam sit amet nisl.</p>
        <p>Elit at imperdiet dui accumsan sit amet nulla. Et malesuada fames ac turpis egestas sed tempus. Morbi tristique senectus et netus et malesuada fames ac. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Volutpat lacus laoreet non curabitur gravida arcu ac. Risus quis varius quam quisque id diam. Auctor urna nunc id cursus. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Magna sit amet purus gravida. Quis viverra nibh cras pulvinar mattis nunc sed blandit. Elementum nibh tellus molestie nunc non blandit massa enim. Faucibus turpis in eu mi bibendum. Dis parturient montes nascetur ridiculus mus mauris.</p>
        <p>Accumsan tortor posuere ac ut consequat semper viverra nam libero. Urna nec tincidunt praesent semper feugiat. Lacus vel facilisis volutpat est. Massa sapien faucibus et molestie. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Leo vel fringilla est ullamcorper eget nulla. Eu augue ut lectus arcu bibendum. A diam maecenas sed enim ut sem viverra. In egestas erat imperdiet sed euismod nisi porta. Risus sed vulputate odio ut enim blandit volutpat maecenas. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris.</p>
        <p>Tristique magna sit amet purus gravida quis blandit turpis. Vel turpis nunc eget lorem dolor. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Tempor id eu nisl nunc. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Donec ultrices tincidunt arcu non sodales neque sodales. Potenti nullam ac tortor vitae purus. Risus pretium quam vulputate dignissim suspendisse in est ante in. Scelerisque varius morbi enim nunc faucibus a. Bibendum enim facilisis gravida neque convallis a. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Vivamus arcu felis bibendum ut tristique. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Elementum tempus egestas sed sed risus pretium. Ullamcorper sit amet risus nullam eget felis eget. Convallis a cras semper auctor neque. Aliquet nec ullamcorper sit amet risus nullam eget. Nulla aliquet porttitor lacus luctus accumsan.</p>
      </div>
    </div>
  );

}

export default WikiHome;